### ISSUE TITLE
Primer evento: presentación de asturias.js

### ISSUE THREAD

**Issue by sergioalvz** [asturiasjs/activities#10]
# Propuesta de charla, taller, hackathon, debate, etc

## Título

Primer evento: presentación de asturias.js

## Descripción

Para este primer evento, propongo hacer una ligera introducción a la comunidad (qué objetivos persigue, cómo está organizada, animar a la participación...) y dejar un espacio abierto de discusión para que las y los asistentes cuentes sus experiencias utilizando el lenguaje.

## ¿A quién va dirigida?

A todo el mundo.

## ¿Necesitas algo?

Nada en especial, más allá de una plataforma de videoconferencia :-)

---

Antes de presentar tu propuesta no olvides leer y respetar [nuestro Código de Conducta](https://github.com/asturiasjs/activities/blob/master/CODE_OF_CONDUCT.md) y asegurar que tu actividad se ajusta a [nuestros términos y condiciones](https://github.com/asturiasjs/activities/blob/master/TERMS.md).

**Comment by SantiMA10** [comment]
Como día me parece buena idea el martes 8 de Junio como habíamos hablado.

En cuanto a la plataforma de videollamada yo conozco dos alternativas gratuitas que nos ofrecen recursos suficientes para el evento (mi duda es la opciones de moderación):

- [ ] https://meet.jit.si/, gratis sin necesidad de cuenta ni de admitir a cada persona de forma individualmente.
- [ ] https://meet.google.com, gratis pero necesita una cuenta de Google, hay límite de 250 participantes y hay que admitir a cada persona (o invitar a todo el mundo a un evento en Google Calendar)

Dejo un bonus de otras que podrían servir pero no en su versión gratuita o no para este tipo de evento.

- [ ] https://discord.com, gratis pero con límite de 25 participantes en videollamadas.
- [ ] https://zoom.us, la versión gratis con límite de 40 minutos si hay más de 3 personas

**Comment by sergioalvz** [comment]
El último evento de AsturiasHacking se hizo con Jitsi Meet y funcionó bastante bien, por mí vamos adelante con ello :-)

Respecto a la fecha, me encaja perfecto ese martes 9 de junio.

**Comment by SantiMA10** [comment]
@sergioalvz @fernandofreije ¿mantendremos algún tipo de log en el README de las actividades?

Pensaba en algo del estilo a lo que genera https://allcontributors.org/ de forma automatica para las contribuciones

**Comment by sergioalvz** [comment]
No había pensado en All Contributors para esto, pero me animaría a probar! :-)

**Comment by SantiMA10** [comment]
Faltaría mirar a ver si se pueden personalizar "los roles" de all contributors

**Comment by sergioalvz** [comment]
Parece que hay una configuración para añadir "roles" nuevos: https://allcontributors.org/docs/en/bot/configuration (ver `types`). Aunque en los roles por defecto hay uno para `talks` que podríamos usar en el corto plazo.

**Comment by sergioalvz** [comment]
[Cierro el issue aunque continúe la conversación]
