### ISSUE TITLE
Propuesta: Introducción a Verdaccio

### ISSUE THREAD

**Issue by juanpicado** [asturiasjs/activities#12]
# Propuesta de actividad

## Título

Introdución a Verdaccio

## Descripción

Tanto si eres backend o front-end y usas Javascript, esta charla es para ti. Alguna vez habras instalado un paquete con `npm install` desde el regitro npmjs. Verdaccio es un registro privado que actua como proxy y cache, open source construido con Node.js. Es un registro muy ligero y multi funcional y con un bonito Interfaz. Si quieres saber mas, no dudes en ver esta charla.

https://github.com/verdaccio/

## ¿A quién va dirigida?

Charla introductoria, cualquier nivel.

## ¿Necesitas algo?

Internet, Zoom o similar.

## Mini bio

Me llamo Juan, soy de Madrid, vivo en Berlin y trabajo para eBay (mobile.de). Soy Front-End Engineer collaborando a construir plataformas de clasificados (actualmente para https://www.kijijiautos.ca/). En mi tiempo libre hago Open Source y dedico mis esfueros en contribuir a Verdaccio (https://verdaccio.org/).

https://twitter.com/jotadeveloper

---

Antes de presentar tu propuesta no olvides leer y respetar [nuestro Código de Conducta](https://github.com/asturiasjs/activities/blob/master/CODE_OF_CONDUCT.md) y asegurar que tu actividad se ajusta a [nuestros términos y condiciones](https://github.com/asturiasjs/activities/blob/master/TERMS.md).

**Comment by SantiMA10** [comment]
Hola! Muchas gracias por la propuesta!

¿Concretamos después de la presentación de asturias.js? Que va a ser el martes 9 de Junio

**Comment by juanpicado** [comment]
Podemos cerrar esto creo :) aqui los slides https://t.co/KQdkeNUH6T?amp=1
